### ISSUE TITLE
p12s Caloric Theory wind radius is inaccurate

### ISSUE THREAD

**Issue by YQL-Skorpion** [PunishXIV/Splatoon#10]
I was clipped by SE wind in this case.  ![image](https://github.com/PunishXIV/Splatoon/assets/72714040/77df67ec-b9d6-4117-b980-d7cbee638ab6)

**Comment by Limiana** [comment]
Hello!
Are you sure it wasn't snapshot? The line is made exactly based on AOE animation
Or maybe it's the case where real aoe is larger than drawn... I can increase it a bit to ensure safety but it's not easy to test this stuff

**Comment by YQL-Skorpion** [comment]
> Hello! Are you sure it wasn't snapshot? The line is made exactly based on AOE animation Or maybe it's the case where real aoe is larger than drawn... I can increase it a bit to ensure safety but it's not easy to test this stuff

Hi! I believe the animation has two parts --- a smaller circle and a much larger one immediately following. Splatoon seems to be the smaller one. However, we've wiped two times due to E/W pair getting clipped by one of the winds, though according to the scripts the safe spot is rather large. If I have more observations, I will let you know.

**Comment by Limiana** [comment]
I was able to see that brief animation when I looked closely. The preset it adjusted to match that animation radius, hopefully that's correct. Thank you!
