### ISSUE TITLE
Scripts are not importing

### ISSUE THREAD

**Issue by GrndFress** [PunishXIV/Splatoon#11]
Hello. Ive tried to import the new 10s script (Tether cones.) but when i copy the link and import it, the plugin says "Downloading script from trusted URL" but when i go to the "Scripts" tab, it doesnt show anything. ive tried it with other scripts as well and it does the same thing. Ive imported few scripts before and it always worked, untill today (after the FFXIVQuickLauncher update). Wonder if there is some way to fix it.

**Comment by Limiana** [comment]
Hello, please attach your `%appdata%\XIVLauncher\dalamud.log`

**Comment by Limiana** [comment]
just for the good measure I tried to import scripts on a fresh installation and everything seems to be fine:
![image](https://github.com/PunishXIV/Splatoon/assets/5073202/428047be-c693-4e2f-8142-015734f9fdcc)

**Comment by GrndFress** [comment]
I have restarted my PC, and it is suddenly working, I have no idea what caused it but, everything is working as it should. Apologies for the confusion. Thank you for the quick reply and for all the hard work.
