### ISSUE TITLE
I have a question regarding the position of the sunrise cannon guidance in the second half of savage 4.

### ISSUE THREAD

**Issue by luv0450** [PunishXIV/Splatoon#111]
Thank you very much for all your help.
I have a question regarding the position of the sunrise cannon guidance in the second half of savage 4.
Currently, in Japan, the sunrise is guided clockwise from the northwest and counterclockwise from the southwest of the dps.
I am very sorry, but would it be possible to add this cannon guiding position?
I apologize if the text is not correct because I am using a translation site.
![画像_2024-08-06_102416987](https://github.com/user-attachments/assets/6cf70403-9ab1-431b-8f92-91a02fe0e3bf)

**Comment by Limiana** [comment]
Added setting, "start from west instead of north" which should match your guide. Please check it and report if it works

**Comment by Limiana** [comment]
Assuming it works then, if not, please open another issue
