### ISSUE TITLE
New Splatoon repoUrl doesn't show in the plugin loader

### ISSUE THREAD

**Issue by GrndFress** [PunishXIV/Splatoon#2]
I have the Puni.sh Repository added but Splatoon doesn't show at all, it keeps showing the old outdated one (other Puni.sh plugins do show)

**Comment by kawaii** [comment]
The plugin installer is a little temperamental when it comes to duplicate plugins - especially if you already have it installed from a previous source. You should totally uninstall your original copy of Splatoon, close and reopen the plugin installer, and you should be able to identify the correct version of Splatoon on the new repo then. Your configs and existing presets will not be effected.

**Comment by GrndFress** [comment]
Got it, fixed. Thank you for the fast response
