### ISSUE TITLE
[Bug] Cone offset uses absolute coordinates, rather that target-relative

### ISSUE THREAD

**Issue by kaedys** [PunishXIV/Splatoon#20]
I'm trying to make a conal display for Oschon's mechanic where he summons an avatar telegraphs a cone attack facing a corner, but that avatar goes through a 225 degree rotation and lands on one of the adjacent edges of the room before firing it.  This requires a 225 degree cone rotation, which is fine, already supported.  However, it also requires a 10x15 offset for the cone to originate from the adjacent wall.  This works fine for one, but the same offset applied to an avatar that spawns in a different corner results in the incorrect offset, because the offset is relative to the absolute grid, rather than the facing of the target the cone is relative to.  As an example, if a target is facing north, and you set the cone offset to be y=-10, it'll spawn 10y in front of that target.  If the target turns around and casts the same cone, the same -10 offset will cause it to be _behind_ the target, because the y axis is the absolute axis for the instance, not the target.  If the target faced east, the same offset would cause it to be to their left.  The cone itself will still rotation, but the origin point of the cone won't rotate with the target.

Images to clarify:

Clone is in north-west corner, rotating to the right, so offset used is x=10.0, y=-15.0:

![20231007-170147-6855f3](https://github.com/PunishXIV/Splatoon/assets/9020449/fbee66a6-6b37-4653-a725-9a8e58e95332)

Clone in the north-east corner this time.  The same offset causes the cone to originate from off the field, rather than in the proper place:

![20231007-170220-a50779](https://github.com/PunishXIV/Splatoon/assets/9020449/37f610ff-038f-42c3-b2ee-1748868ba2c5)

Obviously, with a target-relative offset, the offset values I'm using will need to change (napkin trig says it should be ~ x=17.68, y=-3.54), but it should mean the _same_ offset can be used for all 4 corners, since it'll be offset relative to the facing of the avatar, rather than the absolute grid in the instance.

**Comment by Limiana** [comment]
should be fixed now

**Comment by kaedys** [comment]
Working perfectly, much appreciated!
