### ISSUE TITLE
issue loading TOP layouts after updating to version 3.4.1.0 

### ISSUE THREAD

**Issue by heyimbrandon** [PunishXIV/Splatoon#52]
multiple layouts not working as of this update, can confirm still working on 3.4.0.9 the list of the ones we've experienced so far are listed below. 

mf clone attacks, optical unit finder,  arm turning bait spots, Omega cleave left and right, delta final spots

**Comment by Limiana** [comment]
Hello! Please update the plugin to 3.4.1.2, the issue should be fixed there. Please let me know if it's working correctly

**Comment by heyimbrandon** [comment]
Updated and tested, everything is working correctly now.  Thank you for the quick fix!
