### ISSUE TITLE
Some waymarks don't appear after hotfix (May 12, 2024)

### ISSUE THREAD

**Issue by glen-lee** [PunishXIV/Splatoon#65]
Greetings. I have noticed that after the FFXIV hotfix today (May 12 2024),  waymarks that normally appear on DSR, didnt show up. Before the hotfix everything was fine. These are the markers affected that I noticed:

1. P1 donut aoe wont show up
2. P2 trio dash wont show up
3. P2 finding Thordan early - the arrow appears but lasts quicker than usual before disappearing
4. P2 inner knight directions wont show up
5. P2 DRK tether and safe spots (DRK relative strat during sanc) wont show up

I dont know if this is actually because of  the hotfix or if its something on my end. But i have changed nothing on my PC before and after the hotfix, so I thought Id put it here. I have tried to restart my PC as well.

**Comment by Limiana** [comment]
Hello! Did you possibly relogged into the game? You would need to type `/splatoon` and select correct phase in top right corner in that case

**Comment by glen-lee** [comment]
> Hello! Did you possibly relogged into the game? You would need to type `/splatoon` and select correct phase in top right corner in that case

That must be the case then, I had multiple DCs due to DDOS... been getting bad lately and it must have screwed with the Phase selection. It works fine right now. Thanks.
