### ISSUE TITLE
Indicators not aligning where expected

### ISSUE THREAD

**Issue by kaedys** [PunishXIV/Splatoon#67]
![20240702-221918-941248](https://github.com/PunishXIV/Splatoon/assets/9020449/feb3faf4-f72e-4a64-a8fe-19efc1b3451d)

Both circles there are supposed to be centered on an entity, and were prior to DT.  The purple one near the bottom and the bright purple cross at its center should be centered on my character.  The red, yellow, and teal circles near to the top left should be centered on the _right_ of the two mobs.  The indicators also have very odd vertical behavior.  The ones on my character, for example, are vertically set several feet above my character's head, moving as I move up or down the slope.  However, if I zoom the camera in, the markers move downwards and towards my character, _almost_ reaching the proper position when the camera is at minimum distance to my character (without entering first person):

![20240702-222821-97a43d](https://github.com/PunishXIV/Splatoon/assets/9020449/55b5dd7d-5297-4ccf-87be-4ce43142621d)
![20240702-222826-8e7a03](https://github.com/PunishXIV/Splatoon/assets/9020449/008cdb82-f939-4d18-8454-1324859ce046)
![20240702-222830-6aad87](https://github.com/PunishXIV/Splatoon/assets/9020449/a897a1ef-14e5-450d-8209-35fcec417e6e)

I'm not sure if it's related, but my Dalamud scaling is set at 117%, my UI settings in the game are at 150%, with a base resolution of 4k (Borderless Windowed).  All of these markers were working as expected prior to DT and the latest release of this mod.  Mod config attached.  Lemme know if there's anything else you need.

[configV1.json](https://github.com/user-attachments/files/16076308/configV1.json)

**Comment by Limiana** [comment]
Hello! Please go to system settings - graphics settings, and disable "dynamic resolution"

**Comment by kaedys** [comment]
Yep, that does appear to have fixed the issue, much appreciated.

**Comment by kvinksb** [comment]
Hi is there a way to fix that problem but with the 3D Resolution Scaling to 50 and Enable dynamic resolution off? seems like switching   3D Resolution Scaling 100 to 50 de-escalate the presets , thanks!
![Capture](https://github.com/PunishXIV/Splatoon/assets/155389035/7d0e0990-95b3-4f8a-9ff5-18350350f171)

**Comment by IrisAinsworth** [comment]
When playing in windowed mode, the drawing seems to be based on the upper left corner of the monitor.
This also occurs when "Dynamic Resolution" is disabled and "3D Resolution Scaling" is set to 100.
Prior to the DT, the drawing was done without problems.
I hope this helps you to solve the problem.

**Comment by kvinksb** [comment]
I try to disable/enable the options your mention but didn't work all seems related to if i low the 3d resolution numbers less then 100, if it 100  the presets works perfect and lower doesn't, i was just tryin to not keep it at 100 because i lost too much fps, but thanks for the help!

**Comment by sader4** [comment]
Is there any way to make Splatoon respect the 3D resolution scaling and scale back up? Had to start using this setting because the graphics update makes low FPS on 100.

**Comment by Limiana** [comment]
> Is there any way to make Splatoon respect the 3D resolution scaling and scale back up? Had to start using this setting because the graphics update makes low FPS on 100.

Hello! Yes, I'm working on it but it will take some time

**Comment by sourpuh** [comment]
This should be fixed now. Let me know if there's any further issues.

**Comment by IrisAinsworth** [comment]
> When playing in windowed mode, the drawing seems to be based on the upper left corner of the monitor. This also occurs when "Dynamic Resolution" is disabled and "3D Resolution Scaling" is set to 100. Prior to the DT, the drawing was done without problems. I hope this helps you to solve the problem.

This problem has not been resolved in Splatoon 3.5.1.2.
However, disabled `Enable multi-monitor windows` option in Dalamud worked fine.

Is it safe to assume that this is more of a Dalamud problem than a Splatoon problem?

**Comment by sourpuh** [comment]
I wasn't aware of the `Enable multi-monitor windows` issue. Fix is incoming.

**Comment by Limiana** [comment]
Should be fixed now
